version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.1  # Use a newer version of PostGIS with PostgreSQL 13
    environment:
      POSTGRES_DB: geotalk_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  django:
    build: ./geotalk
    volumes:
      - ./geotalk:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  nextjs:
    build: ./geotalk-frontend
    volumes:
      - ./geotalk-frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - django

