# Generated by Django 4.2.16 on 2024-09-14 17:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geodata',
            old_name='raster_file',
            new_name='raster_data',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='geojson_data',
        ),
        migrations.AddField(
            model_name='geodata',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='geodata',
            name='vector_data',
            field=models.FileField(blank=True, null=True, upload_to='vectors/'),
        ),
    ]
